// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Agent struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Status         string         `json:"status"`
	LastSeen       sql.NullTime   `json:"last_seen"`
	CreatedAt      time.Time      `json:"created_at"`
	RemoteClientID sql.NullString `json:"remote_client_id"`
}

type RemoteClient struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}
