// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"
)

type Querier interface {
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateRemoteClient(ctx context.Context, arg CreateRemoteClientParams) (RemoteClient, error)
	DeleteAgent(ctx context.Context, id string) error
	DeleteRemoteClient(ctx context.Context, id string) error
	GetAgent(ctx context.Context, id string) (Agent, error)
	GetAgentByName(ctx context.Context, name string) (Agent, error)
	GetRemoteClient(ctx context.Context, id string) (RemoteClient, error)
	GetRemoteClientByName(ctx context.Context, name string) (RemoteClient, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListRemoteClients(ctx context.Context) ([]RemoteClient, error)
	UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error)
	UpdateRemoteClientStatus(ctx context.Context, arg UpdateRemoteClientStatusParams) (RemoteClient, error)
}

var _ Querier = (*Queries)(nil)
